VERSION="5.8.3"
PACKAGE="xz-${VERSION}"
TARBALL="$PACKAGE.tar.gz"
URL="https://github.com/tukaani-project/xz/releases/download/v$VERSION/$TARBALL"
BUILD_DEP="xz-utils"
UPSTREAM_GITHUB="tukaani-project/xz"
