VERSION="34.2"
PACKAGE="kmod-${VERSION}"
TARBALL="v${VERSION}.tar.gz"
URL="https://github.com/kmod-project/kmod/archive/refs/tags/$TARBALL"
EXTRA_DEPS="zlib1g-dev"
UPSTREAM_GITHUB="kmod-project/kmod"
